# Generated by Django 2.2.2 on 2019-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('venue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_list',
                'managed': False,
            },
        ),
    ]
